//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complemento
    {
        public Complemento()
        {
            this.Detalle_Pedido = new HashSet<Detalle_Pedido>();
        }
    
        public string complemento_id { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<int> stock { get; set; }
    
        public virtual ICollection<Detalle_Pedido> Detalle_Pedido { get; set; }
    }
}
