//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Pedido
    {
        public string detalle_id { get; set; }
        public string pedido_id { get; set; }
        public string helado_id { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public string topping_id { get; set; }
        public string complemento_id { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual Complemento Complemento { get; set; }
        public virtual Helado Helado { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
