//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Helado
    {
        public Helado()
        {
            this.Detalle_Pedido = new HashSet<Detalle_Pedido>();
            this.Helado_Promocion = new HashSet<Helado_Promocion>();
            this.Ingrediente = new HashSet<Ingrediente>();
            this.Resena = new HashSet<Resena>();
        }
    
        public string helado_id { get; set; }
        public string sabor_id { get; set; }
        public string tamano_id { get; set; }
        public decimal precio_base { get; set; }
        public Nullable<bool> en_stock { get; set; }
        public string imagen_url { get; set; }
    
        public virtual ICollection<Detalle_Pedido> Detalle_Pedido { get; set; }
        public virtual Sabor Sabor { get; set; }
        public virtual Tamano_Helado Tamano_Helado { get; set; }
        public virtual ICollection<Helado_Promocion> Helado_Promocion { get; set; }
        public virtual ICollection<Ingrediente> Ingrediente { get; set; }
        public virtual ICollection<Resena> Resena { get; set; }
    }
}
