//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Helado_Promocion
    {
        public string helado_promocion_id { get; set; }
        public string helado_id { get; set; }
        public string promocion_id { get; set; }
    
        public virtual Helado Helado { get; set; }
        public virtual Promocion Promocion { get; set; }
    }
}
