//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingrediente
    {
        public Ingrediente()
        {
            this.Inventario = new HashSet<Inventario>();
        }
    
        public string ingrediente_id { get; set; }
        public string nombre { get; set; }
        public string proveedor_id { get; set; }
        public string helado_id { get; set; }
        public string unidad_medida { get; set; }
        public Nullable<decimal> precio_por_unidad { get; set; }
        public string descripcion { get; set; }
    
        public virtual Helado Helado { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual ICollection<Inventario> Inventario { get; set; }
    }
}
