//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria_CRUD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HeladeriaEntities : DbContext
    {
        public HeladeriaEntities()
            : base("name=HeladeriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categoria_Helado> Categoria_Helado { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Complemento> Complemento { get; set; }
        public DbSet<Detalle_Pedido> Detalle_Pedido { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Helado> Helado { get; set; }
        public DbSet<Helado_Promocion> Helado_Promocion { get; set; }
        public DbSet<Ingrediente> Ingrediente { get; set; }
        public DbSet<Inventario> Inventario { get; set; }
        public DbSet<Metodo_Pago> Metodo_Pago { get; set; }
        public DbSet<Pedido> Pedido { get; set; }
        public DbSet<Promocion> Promocion { get; set; }
        public DbSet<Proveedor> Proveedor { get; set; }
        public DbSet<Resena> Resena { get; set; }
        public DbSet<Sabor> Sabor { get; set; }
        public DbSet<Tamano_Helado> Tamano_Helado { get; set; }
        public DbSet<Topping> Topping { get; set; }
        public DbSet<Turno_Empleado> Turno_Empleado { get; set; }
    
        public virtual ObjectResult<spActualizarCategoria_Result> spActualizarCategoria(string categoria_id, string nombre, string descripcion)
        {
            var categoria_idParameter = categoria_id != null ?
                new ObjectParameter("categoria_id", categoria_id) :
                new ObjectParameter("categoria_id", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spActualizarCategoria_Result>("spActualizarCategoria", categoria_idParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<spActualizarSabor_Result> spActualizarSabor(string sabor_id, string nombre, string descripcion, string categoria_id, Nullable<bool> es_popular)
        {
            var sabor_idParameter = sabor_id != null ?
                new ObjectParameter("sabor_id", sabor_id) :
                new ObjectParameter("sabor_id", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var categoria_idParameter = categoria_id != null ?
                new ObjectParameter("categoria_id", categoria_id) :
                new ObjectParameter("categoria_id", typeof(string));
    
            var es_popularParameter = es_popular.HasValue ?
                new ObjectParameter("es_popular", es_popular) :
                new ObjectParameter("es_popular", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spActualizarSabor_Result>("spActualizarSabor", sabor_idParameter, nombreParameter, descripcionParameter, categoria_idParameter, es_popularParameter);
        }
    
        public virtual ObjectResult<spAgregarCategoria_Result> spAgregarCategoria(string categoria_id, string nombre, string descripcion)
        {
            var categoria_idParameter = categoria_id != null ?
                new ObjectParameter("categoria_id", categoria_id) :
                new ObjectParameter("categoria_id", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAgregarCategoria_Result>("spAgregarCategoria", categoria_idParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<spAgregarSabor_Result> spAgregarSabor(string sabor_id, string nombre, string descripcion, string categoria_id, Nullable<bool> es_popular)
        {
            var sabor_idParameter = sabor_id != null ?
                new ObjectParameter("sabor_id", sabor_id) :
                new ObjectParameter("sabor_id", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var categoria_idParameter = categoria_id != null ?
                new ObjectParameter("categoria_id", categoria_id) :
                new ObjectParameter("categoria_id", typeof(string));
    
            var es_popularParameter = es_popular.HasValue ?
                new ObjectParameter("es_popular", es_popular) :
                new ObjectParameter("es_popular", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAgregarSabor_Result>("spAgregarSabor", sabor_idParameter, nombreParameter, descripcionParameter, categoria_idParameter, es_popularParameter);
        }
    
        public virtual ObjectResult<spBuscarCategoria_Result> spBuscarCategoria(string texto, string criterio)
        {
            var textoParameter = texto != null ?
                new ObjectParameter("Texto", texto) :
                new ObjectParameter("Texto", typeof(string));
    
            var criterioParameter = criterio != null ?
                new ObjectParameter("Criterio", criterio) :
                new ObjectParameter("Criterio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBuscarCategoria_Result>("spBuscarCategoria", textoParameter, criterioParameter);
        }
    
        public virtual ObjectResult<spBuscarSabor_Result> spBuscarSabor(string texto, string criterio)
        {
            var textoParameter = texto != null ?
                new ObjectParameter("Texto", texto) :
                new ObjectParameter("Texto", typeof(string));
    
            var criterioParameter = criterio != null ?
                new ObjectParameter("Criterio", criterio) :
                new ObjectParameter("Criterio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBuscarSabor_Result>("spBuscarSabor", textoParameter, criterioParameter);
        }
    
        public virtual ObjectResult<spEliminarCategoria_Result> spEliminarCategoria(string categoria_id)
        {
            var categoria_idParameter = categoria_id != null ?
                new ObjectParameter("categoria_id", categoria_id) :
                new ObjectParameter("categoria_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEliminarCategoria_Result>("spEliminarCategoria", categoria_idParameter);
        }
    
        public virtual ObjectResult<spEliminarSabor_Result> spEliminarSabor(string sabor_id)
        {
            var sabor_idParameter = sabor_id != null ?
                new ObjectParameter("sabor_id", sabor_id) :
                new ObjectParameter("sabor_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEliminarSabor_Result>("spEliminarSabor", sabor_idParameter);
        }
    
        public virtual ObjectResult<spListarCategorias_Result> spListarCategorias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spListarCategorias_Result>("spListarCategorias");
        }
    
        public virtual ObjectResult<spListarSabores_Result> spListarSabores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spListarSabores_Result>("spListarSabores");
        }
    }
}
