//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.Detalle_Pedido = new HashSet<Detalle_Pedido>();
        }
    
        public string pedido_id { get; set; }
        public string cliente_id { get; set; }
        public string empleado_id { get; set; }
        public Nullable<System.DateTime> fecha_pedido { get; set; }
        public string metodo_pago_id { get; set; }
        public decimal total { get; set; }
        public string estado { get; set; }
        public string observaciones { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Detalle_Pedido> Detalle_Pedido { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Metodo_Pago Metodo_Pago { get; set; }
    }
}
