//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocion
    {
        public Promocion()
        {
            this.Helado_Promocion = new HashSet<Helado_Promocion>();
        }
    
        public string promocion_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal descuento { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public Nullable<bool> activa { get; set; }
    
        public virtual ICollection<Helado_Promocion> Helado_Promocion { get; set; }
    }
}
