//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resena
    {
        public string resena_id { get; set; }
        public string cliente_id { get; set; }
        public string helado_id { get; set; }
        public int calificacion { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Helado Helado { get; set; }
    }
}
