//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sabor
    {
        public Sabor()
        {
            this.Helado = new HashSet<Helado>();
        }
    
        public string sabor_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string categoria_id { get; set; }
        public Nullable<bool> es_popular { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual Categoria_Helado Categoria_Helado { get; set; }
        public virtual ICollection<Helado> Helado { get; set; }
    }
}
