//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heladeria_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno_Empleado
    {
        public string turno_id { get; set; }
        public string empleado_id { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public System.TimeSpan hora_fin { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
